// Mock data generated from CSV
export const mockCourses = [
  // COMMERCE - Marketing
  {
    id: '1',
    title: 'Google Digital Marketing & E-Commerce Certificate',
    domain: 'COMMERCE',
    subdomain: 'marketing',
    level: 'Beginner',
    duration: '6 months',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce',
    isFeatured: true
  },
  {
    id: '2',
    title: 'Digital Marketing Specialization',
    domain: 'COMMERCE',
    subdomain: 'marketing',
    level: 'Beginner',
    duration: '2 months',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/ai-marketing-mastery',
    isFeatured: true
  },
  {
    id: '3',
    title: 'The Complete Digital Marketing',
    domain: 'COMMERCE',
    subdomain: 'marketing',
    level: 'Beginner',
    duration: '3 months',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/digital-marketing-certification-course',
    isFeatured: false
  },
  // COMMERCE - Accounting
  {
    id: '4',
    title: 'Certified Management Accountant (CMA)',
    domain: 'COMMERCE',
    subdomain: 'accounting',
    level: 'Intermediate',
    duration: '4 weeks',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/packt-certified-associate-in-project-management-capm',
    isFeatured: false
  },
  {
    id: '5',
    title: 'Certified Public Accountant (CPA)',
    domain: 'COMMERCE',
    subdomain: 'accounting',
    level: 'Beginner',
    duration: '4 weeks',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/pearson-certified-associate-in-project-management-capm-exam',
    isFeatured: false
  },
  // COMMERCE - Finance
  {
    id: '6',
    title: 'Chartered Financial Analyst (CFA)',
    domain: 'COMMERCE',
    subdomain: 'finance',
    level: 'Beginner',
    duration: '4 weeks',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/financial-analysis-skills-for-success',
    isFeatured: true
  },
  {
    id: '7',
    title: 'Financial Risk Manager (FRM)',
    domain: 'COMMERCE',
    subdomain: 'finance',
    level: 'Advanced',
    duration: '6 weeks',
    certificateAvailable: true,
    platformName: 'SWAYAM',
    courseURL: 'https://onlinecourses.swayam2.ac.in/imb26_mg02/preview',
    isFeatured: false
  },
  {
    id: '8',
    title: 'Financial Modeling & Valuation Analyst (FMVA)',
    domain: 'COMMERCE',
    subdomain: 'finance',
    level: 'Advanced',
    duration: '12 weeks',
    certificateAvailable: true,
    platformName: 'NPTEL',
    courseURL: 'https://onlinecourses.nptel.ac.in/noc26_mg22/preview',
    isFeatured: false
  },
  // COMMERCE - Stock Market
  {
    id: '9',
    title: 'Practical Guide of Trading',
    domain: 'COMMERCE',
    subdomain: 'stock market basics',
    level: 'Beginner',
    duration: '4 weeks',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/financial-instruments-trading-investing',
    isFeatured: false
  },
  {
    id: '10',
    title: 'Trading Basics',
    domain: 'COMMERCE',
    subdomain: 'stock market basics',
    level: 'Beginner',
    duration: '8 hours',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/learn/trading-basics',
    isFeatured: false
  },
  {
    id: '11',
    title: 'Construct Stock Market Indices',
    domain: 'COMMERCE',
    subdomain: 'stock market basics',
    level: 'Advanced',
    duration: '2 hours',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/projects/construct-stock-market-indices',
    isFeatured: false
  },
  // COMMERCE - Business Analytics
  {
    id: '12',
    title: 'Business Analytics with Excel',
    domain: 'COMMERCE',
    subdomain: 'business analytics',
    level: 'Intermediate',
    duration: '2 weeks',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/learn/business-analytics-excel',
    isFeatured: false
  },
  {
    id: '13',
    title: 'Business Intelligence and Analytics',
    domain: 'COMMERCE',
    subdomain: 'business analytics',
    level: 'Advanced',
    duration: '12 weeks',
    certificateAvailable: true,
    platformName: 'NPTEL',
    courseURL: 'https://onlinecourses.nptel.ac.in/noc26_cs64/preview',
    isFeatured: false
  },
  {
    id: '14',
    title: 'Fundamentals of Business Analytics',
    domain: 'COMMERCE',
    subdomain: 'business analytics',
    level: 'Beginner',
    duration: '8 weeks',
    certificateAvailable: true,
    platformName: 'SWAYAM',
    courseURL: 'https://onlinecourses.swayam2.ac.in/ntr26_ed45/preview',
    isFeatured: false
  },
  // COMMERCE - HR and Entrepreneurship
  {
    id: '15',
    title: 'Human Resource Management: HR for People Managers Specialization',
    domain: 'COMMERCE',
    subdomain: 'HR and entrepreneurship',
    level: 'Beginner',
    duration: '2 months',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/human-resource-management',
    isFeatured: false
  },
  {
    id: '16',
    title: 'Startup Entrepreneurship Specialization',
    domain: 'COMMERCE',
    subdomain: 'HR and entrepreneurship',
    level: 'Beginner',
    duration: '2 months',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/startup-entrepreneurship',
    isFeatured: false
  },
  {
    id: '17',
    title: 'HR Analytics',
    domain: 'COMMERCE',
    subdomain: 'HR and entrepreneurship',
    level: 'Advanced',
    duration: '6 weeks',
    certificateAvailable: true,
    platformName: 'SWAYAM',
    courseURL: 'https://onlinecourses.swayam2.ac.in/imb26_mg53/preview',
    isFeatured: false
  },
  // TECHNOLOGY - Web Development
  {
    id: '18',
    title: 'Full Stack Development',
    domain: 'Technology & Computer Science',
    subdomain: 'Web Development',
    level: 'Beginner',
    duration: '8 months',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/meta-full-stack-developer',
    isFeatured: true
  },
  {
    id: '19',
    title: 'Django for Everybody Specialization',
    domain: 'Technology & Computer Science',
    subdomain: 'Web Development',
    level: 'Intermediate',
    duration: '2 months',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/Django',
    isFeatured: false
  },
  {
    id: '20',
    title: 'Front-End Web Developer',
    domain: 'Technology & Computer Science',
    subdomain: 'Web Development',
    level: 'Advanced',
    duration: '26 weeks',
    certificateAvailable: true,
    platformName: 'edX',
    courseURL: 'https://www.edx.org/certificates/professional-certificate/w3cx-front-end-web-developer',
    isFeatured: false
  },
  // TECHNOLOGY - AI/ML
  {
    id: '21',
    title: 'Introduction to Machine Learning',
    domain: 'Technology & Computer Science',
    subdomain: 'AI/ML',
    level: 'Beginner',
    duration: '12 weeks',
    certificateAvailable: true,
    platformName: 'NPTEL',
    courseURL: 'https://onlinecourses.nptel.ac.in/noc26_cs74/preview',
    isFeatured: true
  },
  {
    id: '22',
    title: 'AI/ML using Python',
    domain: 'Technology & Computer Science',
    subdomain: 'AI/ML',
    level: 'Intermediate',
    duration: '36 hours',
    certificateAvailable: true,
    platformName: 'SWAYAM',
    courseURL: 'https://swayam-plus.swayam2.ac.in/courses/course-details?id=P_IITMPR_089',
    isFeatured: false
  },
  {
    id: '23',
    title: 'Deep Learning',
    domain: 'Technology & Computer Science',
    subdomain: 'AI/ML',
    level: 'Advanced',
    duration: '12 weeks',
    certificateAvailable: true,
    platformName: 'NPTEL',
    courseURL: 'https://onlinecourses.nptel.ac.in/noc25_cs106/preview',
    isFeatured: false
  },
  // TECHNOLOGY - Data Science
  {
    id: '24',
    title: 'Data Science Introductory',
    domain: 'Technology & Computer Science',
    subdomain: 'Data Science',
    level: 'Beginner',
    duration: '12 hours',
    certificateAvailable: true,
    platformName: 'SkillSchool',
    courseURL: 'https://www.skillschool.co.in/courses/free-data-science-certification-training',
    isFeatured: false
  },
  {
    id: '25',
    title: 'Python for Data Science',
    domain: 'Technology & Computer Science',
    subdomain: 'Data Science',
    level: 'Intermediate',
    duration: '3 hours',
    certificateAvailable: true,
    platformName: 'Great Learning',
    courseURL: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/python-for-data-science',
    isFeatured: false
  },
  {
    id: '26',
    title: 'Data Science and Big Data',
    domain: 'Technology & Computer Science',
    subdomain: 'Data Science',
    level: 'Advanced',
    duration: '12 hours',
    certificateAvailable: true,
    platformName: 'SWAYAM',
    courseURL: 'https://www.classcentral.com/course/swayam-mcs-226-data-science-and-big-data-389402',
    isFeatured: false
  },
  // TECHNOLOGY - Cybersecurity
  {
    id: '27',
    title: 'Introduction to Cyber Security',
    domain: 'Technology & Computer Science',
    subdomain: 'Cybersecurity',
    level: 'Beginner',
    duration: '2 hours',
    certificateAvailable: true,
    platformName: 'Simplilearn',
    courseURL: 'https://www.simplilearn.com/learn-cyber-security-basics-skillup',
    isFeatured: false
  },
  {
    id: '28',
    title: 'AI for Cybersecurity Specialization',
    domain: 'Technology & Computer Science',
    subdomain: 'Cybersecurity',
    level: 'Intermediate',
    duration: '6 hours',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/ai-for-cybersecurity',
    isFeatured: false
  },
  {
    id: '29',
    title: 'IBM Cybersecurity Analyst Professional Certificate',
    domain: 'Technology & Computer Science',
    subdomain: 'Cybersecurity',
    level: 'Advanced',
    duration: '12 hours',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst',
    isFeatured: false
  },
  // TECHNOLOGY - Cloud Computing
  {
    id: '30',
    title: 'Introduction to Cloud Computing',
    domain: 'Technology & Computer Science',
    subdomain: 'Cloud Computing',
    level: 'Beginner',
    duration: '2 hours',
    certificateAvailable: true,
    platformName: 'Simplilearn',
    courseURL: 'https://www.simplilearn.com/introduction-to-cloud-computing-basics-skillup',
    isFeatured: false
  },
  {
    id: '31',
    title: 'Cloud Security Practices',
    domain: 'Technology & Computer Science',
    subdomain: 'Cloud Computing',
    level: 'Intermediate',
    duration: '3 hours',
    certificateAvailable: true,
    platformName: 'Great Learning',
    courseURL: 'https://www.mygreatlearning.com/academy/premium/cloud-security-practices',
    isFeatured: false
  },
  {
    id: '32',
    title: 'Cloud Computing Service Models',
    domain: 'Technology & Computer Science',
    subdomain: 'Cloud Computing',
    level: 'Advanced',
    duration: '6 hours',
    certificateAvailable: true,
    platformName: 'Great Learning',
    courseURL: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/cloud-computing-service-models',
    isFeatured: false
  },
  {
    id: '33',
    title: 'Artificial Intelligence on Cloud',
    domain: 'Technology & Computer Science',
    subdomain: 'Cloud Computing',
    level: 'Advanced',
    duration: '12 hours',
    certificateAvailable: true,
    platformName: 'Great Learning',
    courseURL: 'https://www.mygreatlearning.com/academy/learn-for-free/courses/ai-on-cloud',
    isFeatured: false
  },
  // ARTS & HUMANITIES - Psychology
  {
    id: '34',
    title: 'Introduction to Psychology',
    domain: 'Arts & Humanities',
    subdomain: 'psychology',
    level: 'Beginner',
    duration: '7 days',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/learn/introduction-psychology',
    isFeatured: false
  },
  {
    id: '35',
    title: 'Basics of Mental Health and Clinical Psychology',
    domain: 'Arts & Humanities',
    subdomain: 'psychology',
    level: 'Intermediate',
    duration: '8 weeks',
    certificateAvailable: true,
    platformName: 'NPTEL',
    courseURL: 'https://onlinecourses.nptel.ac.in/noc23_ge19/preview',
    isFeatured: false
  },
  {
    id: '36',
    title: 'Harvard: Fundamentals of Neurology',
    domain: 'Arts & Humanities',
    subdomain: 'psychology',
    level: 'Advanced',
    duration: '5 weeks',
    certificateAvailable: true,
    platformName: 'edX',
    courseURL: 'https://www.edx.org/learn/neuroscience/harvard-university-fundamentals-of-neuroscience-part-1-the-electrical-properties-of-the-neuron',
    isFeatured: true
  },
  // ARTS & HUMANITIES - Sociology
  {
    id: '37',
    title: 'Introduction to Sociology',
    domain: 'Arts & Humanities',
    subdomain: 'sociology',
    level: 'Beginner',
    duration: '2 weeks',
    certificateAvailable: true,
    platformName: 'Alison',
    courseURL: 'https://alison.com/course/basics-of-sociology',
    isFeatured: false
  },
  {
    id: '38',
    title: 'Modern Social Theory',
    domain: 'Arts & Humanities',
    subdomain: 'sociology',
    level: 'Intermediate',
    duration: '1 week',
    certificateAvailable: true,
    platformName: 'Cursa',
    courseURL: 'https://cursa.app/free-courses-sociology-online',
    isFeatured: false
  },
  {
    id: '39',
    title: 'Sociology',
    domain: 'Arts & Humanities',
    subdomain: 'sociology',
    level: 'Advanced',
    duration: '3 weeks',
    certificateAvailable: true,
    platformName: 'Saylor',
    courseURL: 'https://learn.saylor.org/course/index.php?categoryid=24',
    isFeatured: false
  },
  // DESIGN - Graphic Design
  {
    id: '40',
    title: 'Fundamentals of Graphic Designing',
    domain: 'Design & Creative Fields',
    subdomain: 'graphic designing',
    level: 'Beginner',
    duration: '1 week',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/learn/fundamentals-of-graphic-design',
    isFeatured: false
  },
  {
    id: '41',
    title: 'Graphic Design Specialisation',
    domain: 'Design & Creative Fields',
    subdomain: 'graphic designing',
    level: 'Intermediate',
    duration: '8 weeks',
    certificateAvailable: true,
    platformName: 'Coursera',
    courseURL: 'https://www.coursera.org/specializations/graphic-design',
    isFeatured: false
  },
  {
    id: '42',
    title: 'Advanced Graphic Design',
    domain: 'Design & Creative Fields',
    subdomain: 'graphic designing',
    level: 'Advanced',
    duration: '6 weeks',
    certificateAvailable: true,
    platformName: 'Udemy',
    courseURL: 'https://www.udemy.com/course/professional-logo-design-crash-course/',
    isFeatured: false
  },
  // DESIGN - Video Editing
  {
    id: '43',
    title: 'Video Editing Basics',
    domain: 'Design & Creative Fields',
    subdomain: 'video editing',
    level: 'Beginner',
    duration: '1 week',
    certificateAvailable: true,
    platformName: 'SkillSchool',
    courseURL: 'https://www.skillschool.co.in/courses/free-video-editing-course',
    isFeatured: false
  },
  {
    id: '44',
    title: 'Video Editing Catalog',
    domain: 'Design & Creative Fields',
    subdomain: 'video editing',
    level: 'Intermediate',
    duration: '2 weeks',
    certificateAvailable: true,
    platformName: 'Udemy',
    courseURL: 'https://www.udemy.com/course/adobe-premiere-pro-masterclass/',
    isFeatured: false
  },
  {
    id: '45',
    title: 'Professional Video Editing',
    domain: 'Design & Creative Fields',
    subdomain: 'video editing',
    level: 'Advanced',
    duration: '1 week',
    certificateAvailable: true,
    platformName: 'Udemy',
    courseURL: 'https://www.udemy.com/course/professional-video-editing/',
    isFeatured: false
  }
]
